services:
  traefik:
    image: traefik:v3.1
    container_name: traefik
    restart: unless-stopped
    command:
      - --api.insecure=false
      - --api.dashboard=true
      - --providers.docker
      - --log.filePath=/log/traefik.log
      - --log.format=json
      - --entrypoints.web.address=:80
      - --entrypoints.dashboard.address=:8080
    ports:
      - ${WEB_PORT}:80
      - ${DASHBOARD_PORT}:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - .data/log:/log
      - ./traefik-users.htpasswd:/traefik-users.htpasswd
    labels:
      - traefik.http.routers.dashboard.rule=Host(`${HOST}`)
      - traefik.http.routers.dashboard.service=api@internal
      - traefik.http.routers.dashboard.entrypoints=dashboard
      - traefik.http.routers.dashboard.middlewares=auth
      - traefik.http.middlewares.auth.basicauth.usersfile=/traefik-users.htpasswd

    networks:
      - traefik-net

networks:
  traefik-net:
    external: true
